### ISSUE TITLE
Update JSON Contract

### ISSUE THREAD

**Issue by lauraguerra1** [AI-Project-Planner/project_planner_be#5]
- Add a tagline: Ask AI for a 5 word description of the app 
- Collaborators: This is missing (should be a number) 
- Change Mock Server to have user_id be an integer and saved be a boolean

**Comment by garrettgregor** [comment]
@lauraguerra1 @sakisandrac @fernandorobles97 Postman should be updated. Lmk if you have any other issues or comments!
